baseURL = "https://thaoeu.site/"
languageCode = "zh-cn"
title = "ThAoeu"
theme = "pass"
hasCJKLanguage = true #中日韩语支持
summaryLength = 89	#摘要字数

[author]
	name = "标杆杆"
	homepage = "https://thaoeu.site"

[params]
	author = "标杆杆"
	subtitle = "With great power comes great responsibility."
	keywords = "vim go"
	toc = true
	registerInfo = "黑ICP备19007841号-2"


[markup]
	[markup.highlight]
	lineNos = true
	style = "github"

