baseURL = "https://lrrc.cc/"
languageCode = "zh-cn"
title = "标杆杆栈"
theme = "fkqy"
hasCJKLanguage = true #中日韩语支持
summaryLength = 63	#摘要字数

[author]
	name = "标杆杆"
	homepage = "blog.lrrc.cc"

[params]
	author = "标杆杆"
	subtitle = "一个人的疯言疯语。"
	keywords = "这里没有技术，只有情绪。"
	toc = true

[menu]

  [[menu.main]]
    identifier = "books"
    name = "新书"
    url = "/books/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

[markup]
	[markup.highlight]
	lineNos = true
	style = "github"

